---
# rpmfusion free/nonefree and rpmshere
- name: Install RPM Fusion free and nonfree repository
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_version'] | int }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_version'] | int }}.noarch.rpm"
    state: present
  become: true

- name: Enable fedora-cisco-openh264 repository
  ansible.builtin.command:
    cmd: "dnf config-manager setopt fedora-cisco-openh264.enabled=1"
  become: true

- name: Install RPM Sphere repository
  ansible.builtin.dnf:
    name: "https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-40-1.noarch.rpm"
    state: present
  become: true
